name: CI

on:
  workflow_dispatch:
  push:

jobs:
  default:
    strategy:
      fail-fast: false
      matrix:
        distro: [one]

    name: "${{ matrix.distro }}"
    runs-on: ubuntu-24.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Run industrial_ci
        uses: rhaschke/industrial_ci@master
        env:
          ROS_DISTRO: ${{ matrix.distro }}
          TARGET_CMAKE_ARGS: >
            -DCMAKE_BUILD_TYPE=Debug
            -DCMAKE_CXX_FLAGS="-Werror --coverage -O2 -fno-omit-frame-pointer"

      - name: Generate codecov report
        uses: rhaschke/lcov-action@main
        with:
          lcov_capture_args: --ignore-errors=gcov,mismatch
          ignore: '"*/target_ws/build/*" "*/target_ws/install/*" "*/test/*"'

  deploy:
    if: always()
    needs: default
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Deploying..."

  result:
    if: always()
    needs: [default, deploy]
    runs-on: ubuntu-24.04
    steps:
      - run: |
          for s in ${{ join(needs.*.result, ' ') }}; do
            echo "$s"
            if [ "$s" != "success" ] ; then
              exit 1
            fi
          done
