name: CI

on:
  workflow_dispatch:
  push:

jobs:
  default:
    runs-on: ubuntu-latest
    name: output test
    steps:
      - name: Cache1
        uses: rhaschke/cache@main
        with:
          path: data1
          key: ${{ runner.os }}-data1-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-data1-

      - name: Cache2
        uses: rhaschke/cache@main
        with:
          path: data2
          key: ${{ runner.os }}-data2-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-data2-
        env:
          GHA_CACHE_SAVE: 'always'

      - name: Generate Data
        run: |
          echo "generate data $(date)" > data1
          echo "generate data $(date)" > data2

      - name: Show Data
        run: |
          cat data
          false
