name: CI

on:
  workflow_dispatch:
  push:

jobs:
  default:
    strategy:
      fail-fast: false
      matrix:
        env:
          - IMAGE: melodic
          - IMAGE: noetic

    runs-on: ubuntu-latest
    name: ${{ matrix.env.IMAGE }}
    env:
      DOCKER_IMAGE: ros:${{ matrix.env.IMAGE }}-ros-core
      UPSTREAM_WORKSPACE: github:ros-planning/moveit_msgs#master
      BEFORE_SETUP_UPSTREAM_WORKSPACE: |
        apt-get -qq update
        apt-get -qq install -y --no-upgrade --no-install-recommends git
        git --version

    steps:
      - uses: actions/checkout@v2
      - name: industrial_ci
        uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
