name: CI

on:
  workflow_dispatch:
  push:

jobs:
  default:

    name: "${{ matrix.distro }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test multi-line output
        run: |
          echo "::warning::multi%0D%0Aline"

      - run: |
          echo "GITHUB_ENV=$GITHUB_ENV"
          echo "GITHUB_OUTPUT=$GITHUB_OUTPUT"
          echo "GITHUB_PATH=$GITHUB_PATH"
          echo "GITHUB_STATE=$GITHUB_STATE"
          echo "GITHUB_STEP_SUMMARY=$GITHUB_STEP_SUMMARY"

      - run: ls -R $HOME/work/_temp

      - uses: rhaschke/docker-run-action@v4
        name: env
        with:
          image: ubuntu
          run: env

      - uses: rhaschke/docker-run-action@v4
        name: Generate GITHUB_OUTPUT
        with:
          image: ubuntu
          run: |
            echo "GITHUB_OUTPUT=$GITHUB_OUTPUT"
            echo "output=foobar" >> "$GITHUB_OUTPUT"
            cat "$GITHUB_OUTPUT"

      - run: cat "$GITHUB_ENV"
      - run: cat "$GITHUB_OUTPUT"
      - run: cat "$GITHUB_PATH"
      - run: cat "$GITHUB_STATE"
      - run: cat "$GITHUB_STEP_SUMMARY"
