name: CI

on:
  workflow_dispatch:
  push:

jobs:
  default:
    runs-on: ubuntu-latest
    name: output test
    steps:
      - name: Set color
        id: random-color-generator
        run: |
          echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT
      - name: Get color
        run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"
