name: CI

on:
  workflow_dispatch:
  push:

jobs:
  default:
    strategy:
      fail-fast: false
      matrix:
        distro: [noetic, one]

    name: "${{ matrix.distro }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run industrial_ci
        uses: rhaschke/industrial_ci@master
        env:
          ROS_DISTRO: ${{ matrix.distro }}
