name: CI

on:
  workflow_dispatch:
  push:

jobs:
  default:
    strategy:
      fail-fast: false
      matrix:
        distro: [noetic]

    env:
      ROS_DISTRO: ${{ matrix.distro }}
      PRERELEASE: true
      BASEDIR: ${{ github.workspace }}/.work
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CACHE_PREFIX: ${{ matrix.distro }}
      GHA_CACHE_SAVE: always

    name: "${{ matrix.distro }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test multi-line output
        run: |
          echo "::warning::multi%0D%0Aline"
