name: CI

on:
  workflow_dispatch:
  push:

jobs:
  default:
    strategy:
      fail-fast: false
      matrix:
        distro: [noetic]

    env:
      ROS_DISTRO: ${{ matrix.distro }}
      PRERELEASE: true
      BASEDIR: ${{ github.workspace }}/.work
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CACHE_PREFIX: ${{ matrix.distro }}
      GHA_CACHE_SAVE: always

    name: "${{ matrix.distro }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache ccache
        uses: rhaschke/cache@main
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ env.CACHE_PREFIX }}-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ccache-${{ env.CACHE_PREFIX }}-${{ github.sha }}
            ccache-${{ env.CACHE_PREFIX }}

      - name: industrial_ci
        uses: rhaschke/industrial_ci@debug-ccache
