name: CI

on:
  push:

jobs:
  step:
    runs-on: ubuntu-latest
    steps:
      - uses: jspricke/ros-deb-builder-action@main
        with:
          ROS_DISTRO: rolling
          DEB_DISTRO: resolute
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
