name: CI

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  default:

    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ros:noetic-ros-base
      AFTER_SETUP_TARGET_WORKSPACE: find $BASEDIR/${PREFIX}target_ws/src -maxdepth 2 -type d -ls

    steps:
      - uses: actions/checkout@v2

      - name: folder
        uses: ipa-mdl/industrial_ci@feature/repository-filter
        env:
          TARGET_WORKSPACE: github:frankaemika/franka_ros#develop,franka_description

      - name: -folder1,folder2
        uses: ipa-mdl/industrial_ci@feature/repository-filter
        env:
          TARGET_WORKSPACE: github:frankaemika/franka_ros#develop,-franka_description,franka_msgs

      - name: -folder1,-folder2
        uses: ipa-mdl/industrial_ci@feature/repository-filter
        env:
          TARGET_WORKSPACE: github:frankaemika/franka_ros#develop,-franka_description,-franka_msgs

      - name: folder1,folder2
        uses: ipa-mdl/industrial_ci@feature/repository-filter
        env:
          TARGET_WORKSPACE: github:frankaemika/franka_ros#develop,franka_description,franka_msgs
