name: CI

on:
  workflow_dispatch:
  push:

jobs:
  default:
    runs-on: ubuntu-latest
    name: output test
    steps:
      - name: Cache
        id: cache
        uses: rhaschke/cache@main
        with:
          path: data
          key: ${{ runner.os }}-primes-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-primes-

      - name: Generate Data
        if: steps.cache.outputs.cache-hit != 'true'
        run: echo "generate data $(date)" > data

      - name: Show Data
        run: |
          cat data
          false
