name: CI

on:
  workflow_dispatch:
    inputs:
      STRING:
        type: string
        description: a string
        required: false
      DEPLOY:
        type: boolean
        description: a boolean
        required: true
        default: true
  push:

jobs:
  step:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "${{ inputs.STRING || 'default' }} ${{ inputs.DEPLOY == '' && true || inputs.DEPLOY }}"
      - run: echo "${{ github.ref }}"

  deploy:
    if: github.run_attempt > 1 ||
        (!cancelled() &&
          (inputs.DEPLOY || github.ref == 'refs/heads/master'))
    needs: step
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Deploying..."
