name: CI

on:
  workflow_dispatch:
  push:

jobs:
  step1:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Step 1 ${MY_ENV_VAR// /-}"; exit 1
        env:
          MY_ENV_VAR: "foo bar broken"

  step2:
    needs: step1
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Step 2"

  deploy:
    if: success() && true
    needs: [step1, step2]
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Deploying..."
